root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ./main.go"
  bin = "./tmp/main serve http"
  full_bin = "./tmp/main serve http"
  include_ext = ["go", "toml", "yaml", "sql"]
  exclude_dir = ["tmp", "vendor", "migrations", "tests", "docs", "api"]
  exclude_regex = ["_test\\.go$"]
  delay = 1000

[log]
  time = false

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
  clean_on_exit = true
